name: Commit Linter

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js